
set_property PACKAGE_PIN W5 [get_ports C]							
	set_property IOSTANDARD LVCMOS33 [get_ports C]
	create_clock -add -name sys_clk_pin -period 10.00 -waveform {0 5} [get_ports C]



set_property PACKAGE_PIN U16 [get_ports {LED[0]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {LED[0]}]
set_property PACKAGE_PIN E19 [get_ports {LED[1]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {LED[1]}]
set_property PACKAGE_PIN U19 [get_ports {LED[2]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {LED[2]}]
set_property PACKAGE_PIN V19 [get_ports {LED[3]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {LED[3]}]
set_property PACKAGE_PIN W18 [get_ports {LED[4]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {LED[4]}]
set_property PACKAGE_PIN U15 [get_ports {LED[5]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {LED[5]}]
set_property PACKAGE_PIN U14 [get_ports {LED[6]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {LED[6]}]
set_property PACKAGE_PIN V14 [get_ports {LED[7]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {LED[7]}]
set_property PACKAGE_PIN V13 [get_ports {LED[8]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {LED[8]}]
set_property PACKAGE_PIN V3 [get_ports {LED[9]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {LED[9]}]
set_property PACKAGE_PIN W3 [get_ports {LED[10]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {LED[10]}]
set_property PACKAGE_PIN U3 [get_ports {LED[11]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {LED[11]}]
set_property PACKAGE_PIN P3 [get_ports {LED[12]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {LED[12]}]
set_property PACKAGE_PIN N3 [get_ports {LED[13]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {LED[13]}]
set_property PACKAGE_PIN P1 [get_ports {LED[14]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {LED[14]}]
set_property PACKAGE_PIN L1 [get_ports {LED[15]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {LED[15]}]
	
	
## Switches
    set_property PACKAGE_PIN V17 [get_ports {mode[0]}]                    
        set_property IOSTANDARD LVCMOS33 [get_ports {mode[0]}]
    set_property PACKAGE_PIN V16 [get_ports {mode[1]}]                    
        set_property IOSTANDARD LVCMOS33 [get_ports {mode[1]}]
#    set_property PACKAGE_PIN W16 [get_ports {D0_2}]                    
#        set_property IOSTANDARD LVCMOS33 [get_ports {D0_2}]
#    set_property PACKAGE_PIN W17 [get_ports {D0_3}]                    
#        set_property IOSTANDARD LVCMOS33 [get_ports {D0_3}]                    
        
#    set_property PACKAGE_PIN W15 [get_ports {D1_0}]                    
#        set_property IOSTANDARD LVCMOS33 [get_ports {D1_0}]
#    set_property PACKAGE_PIN V15 [get_ports {D1_1}]                    
#        set_property IOSTANDARD LVCMOS33 [get_ports {D1_1}]
#    set_property PACKAGE_PIN W14 [get_ports {D1_2}]                    
#        set_property IOSTANDARD LVCMOS33 [get_ports {D1_2}]
#    set_property PACKAGE_PIN W13 [get_ports {D1_3}]                    
#        set_property IOSTANDARD LVCMOS33 [get_ports {D1_3}]
    set_property PACKAGE_PIN V2 [get_ports {key_user[0]}]                    
        set_property IOSTANDARD LVCMOS33 [get_ports {key_user[0]}]
    set_property PACKAGE_PIN T3 [get_ports {key_user[1]}]                    
        set_property IOSTANDARD LVCMOS33 [get_ports {key_user[1]}]
    set_property PACKAGE_PIN T2 [get_ports {key_user[2]}]                    
        set_property IOSTANDARD LVCMOS33 [get_ports {key_user[2]}]
    set_property PACKAGE_PIN R3 [get_ports {key_user[3]}]                    
        set_property IOSTANDARD LVCMOS33 [get_ports {key_user[3]}]
    set_property PACKAGE_PIN W2 [get_ports {key_user[4]}]                    
        set_property IOSTANDARD LVCMOS33 [get_ports {key_user[4]}]
    set_property PACKAGE_PIN U1 [get_ports {key_user[5]}]                    
        set_property IOSTANDARD LVCMOS33 [get_ports {key_user[5]}]
    set_property PACKAGE_PIN T1 [get_ports {key_user[6]}]                    
        set_property IOSTANDARD LVCMOS33 [get_ports {key_user[6]}]
    set_property PACKAGE_PIN R2 [get_ports {key_user[7]}]                    
        set_property IOSTANDARD LVCMOS33 [get_ports {key_user[7]}]
     

##Buttons
set_property PACKAGE_PIN U18 [get_ports PB0]						
	set_property IOSTANDARD LVCMOS33 [get_ports PB0]
set_property PACKAGE_PIN T18 [get_ports PB1]						
	set_property IOSTANDARD LVCMOS33 [get_ports PB1]
#USB-RS232 Interface
set_property PACKAGE_PIN B18 [get_ports rx_in]						
	set_property IOSTANDARD LVCMOS33 [get_ports rx_in]
set_property PACKAGE_PIN A18 [get_ports tx_out]						
	set_property IOSTANDARD LVCMOS33 [get_ports tx_out]
	
set_property PACKAGE_PIN W7 [get_ports {cathode[0]}]					
        set_property IOSTANDARD LVCMOS33 [get_ports {cathode[0]}]
    set_property PACKAGE_PIN W6 [get_ports {cathode[1]}]                    
        set_property IOSTANDARD LVCMOS33 [get_ports {cathode[1]}]
    set_property PACKAGE_PIN U8 [get_ports {cathode[2]}]                    
        set_property IOSTANDARD LVCMOS33 [get_ports {cathode[2]}]
    set_property PACKAGE_PIN V8 [get_ports {cathode[3]}]                    
        set_property IOSTANDARD LVCMOS33 [get_ports {cathode[3]}]
    set_property PACKAGE_PIN U5 [get_ports {cathode[4]}]                    
        set_property IOSTANDARD LVCMOS33 [get_ports {cathode[4]}]
    set_property PACKAGE_PIN V5 [get_ports {cathode[5]}]                    
        set_property IOSTANDARD LVCMOS33 [get_ports {cathode[5]}]
    set_property PACKAGE_PIN U7 [get_ports {cathode[6]}]                    
        set_property IOSTANDARD LVCMOS33 [get_ports {cathode[6]}]
    
    
    
    set_property PACKAGE_PIN U2 [get_ports {A[0]}]                    
        set_property IOSTANDARD LVCMOS33 [get_ports {A[0]}]
    set_property PACKAGE_PIN U4 [get_ports {A[1]}]                    
        set_property IOSTANDARD LVCMOS33 [get_ports {A[1]}]
    set_property PACKAGE_PIN V4 [get_ports {A[2]}]                    
        set_property IOSTANDARD LVCMOS33 [get_ports {A[2]}]
    set_property PACKAGE_PIN W4 [get_ports {A[3]}]                    
        set_property IOSTANDARD LVCMOS33 [get_ports {A[3]}]
